Uc 100 add modal to information to search result view
nikolai4D/frontEndFramework pull request #24
Opened 2023-02-07 13:46 UTC by SteppbySteph

UC-100-add-modal-to-information-to-search-result-view

## Description & motivation

Creating modal for SearchResult based on "Molecule_ModalSearchResultDetail" which is a modified version of "ModalFrame" (due to unused content in the original version).
- Content is added to modal and styled according to mockup.
- This modal is visible at view --> needs to be modified to instead be shown as a pop-up modal from view.
- Cross at upper right modal removes modal when clicked on. 
- When clicked on "Add to project" new modal pops up based on "Modal" component --> This only works the first time! 

Navbar has not been modified in this ticket. 
No additional logic/functionality to this ticket.

## How to test

Add #UC-100-add-modal-to-information-to-search-result-view at the end of "nd_frontend" in package.json at UrbanCloud-alt1.
Run and start the project from Urban cloud.
Go to view /searchresult

## New tickets to be added

Functionalities and choice of modal to use. 

---
- [x] The ticket is done, OR it's been mentioned why it's not done above

- [x] Removed console.log in code

- [x] Pulled dev into this branch

- [x] Resolved merge conflicts

- [x] The ID of branch is of format "ABC-123"

- [x] Added a reviewer

2023-02-09 07:19 UTC, lmeow requested changes
Nice! We just need to solve this merge conflict. Perhaps it would be better to make this modal appear when clicking on a list item in the search result (since the view is not empty anymore)

2023-02-13 08:33 UTC, SteppbySteph commented
> Nice! We just need to solve this merge conflict. Perhaps it would be better to make this modal appear when clicking on a list item in the search result (since the view is not empty anymore)

Ticket should be working now and match up with mockup. Had to do modify styling of grid in searchresult view, and uncommenting the original code if changes should not be applied here. With changes all content can be seen without need of scrolling.

2023-02-13 08:34 UTC, SteppbySteph reviewed
Reviewed changes and should be looking and working according to mockup.

2023-02-16 11:32 UTC, lmeow requested changes
Just a couple of places to remove console.logs and then it's good to go! 🚀

2023-02-16 13:26 UTC, lmeow approved these changes
Looks great!

Found a bug though:
- When we open the modal and then the second modal, and pick an option from the drop down, both of the modals close. But that's for a future ticket.

2023-02-16 13:26 UTC, merged