Uc 96 create modal for user in navbar
nikolai4D/frontEndFramework pull request #26
Opened 2023-02-08 11:25 UTC by edzonee

UC-96-create-modal-for-user-in-navbar
## Description & motivation
created the modal for usermodal

created the modal for usermodal

## How to test
needs UC-96-create-modal-for-user-in-navbar from UrbanCloud-alt1
run app
run build
go to search view and modal should be there

once the steps above are done, go into the search view.

## New tickets to be added

---
- [x] The ticket is done, OR it's been mentioned why it's not done above

- [x] Removed console.log in code

- [x] Pulled dev into this branch

- [x] Resolved merge conflicts

- [x] The ID of branch is of format "ABC-123"

- [x] Added a reviewer

2023-02-09 07:11 UTC, lmeow requested changes
Great! However, in order to test the PR we need to fix this:

2023-02-09 07:11 UTC, lmeow commented on generics/components/templates/Template_Search_View.mjs
Getting an error that this doesn't exist

2023-02-16 11:33 UTC, lmeow requested changes
Just a couple of places to remove comments and console.logs, and then it's good to go! 🙌

2023-02-17 12:33 UTC, Feldspatt approved these changes

2023-02-17 14:48 UTC, lmeow approved these changes
NICE! 🚀

2023-02-17 14:48 UTC, merged