Uc 99 add modal to information in process view
nikolai4D/frontEndFramework pull request #28
Opened 2023-02-16 09:01 UTC by SteppbySteph

UC-99-add-modal-to-information-in-process-view

## Description & motivation

Creating a modal fpr ListAllProcessView.
- created modal for the view
- created organism with new molecules to be added inside the modal.

## How to test

Add #UC-99-add-modal-to-information-in-process-view at the end of "nd_frontend" in package.json at UrbanCloud.
Run and start the project.
Go to view /process
Click on a list item

## New tickets to be added

---
- [x] The ticket is done, OR it's been mentioned why it's not done above

- [x] Removed console.log in code

- [x] Pulled dev into this branch

- [x] Resolved merge conflicts

- [x] The ID of branch is of format "ABC-123"

- [x] Added a reviewer

2023-02-16 11:51 UTC, lmeow requested changes
Nice! Just to remove console.logs and comments and then it's good to goooo 🚀

2023-02-17 12:49 UTC, Feldspatt approved these changes

2023-02-23 09:30 UTC, SteppbySteph commented
Fixed conflicts, changed styling of user modal in navbar to match mockup. Most updated styling has been done through nesting.

2023-02-23 09:47 UTC, Feldspatt approved these changes

2023-02-23 09:58 UTC, lmeow approved these changes

2023-02-23 09:58 UTC, merged