Uc 93 add modal to information in organisation view
nikolai4D/frontEndFramework pull request #29
Opened 2023-02-16 12:23 UTC by SteppbySteph

UC-93-add-modal-to-information-in-organisation-view

## Description & motivation

Creating a modal to information in organisation view.
- new organism with new molecules added to the modal.

## How to test

Add # UC-93-add-modal-to-information-in-organisation-view at the end of "nd_frontend" in package.json at UrbanCloud
Run and start the project.
Go to view /organisation.
Click on a list item. Modal should pop up.

## New tickets to be added

---
- [x] The ticket is done, OR it's been mentioned why it's not done above

- [x] Removed console.log in code

- [x] Pulled dev into this branch

- [x] Resolved merge conflicts

- [x] The ID of branch is of format "ABC-123"

- [x] Added a reviewer

2023-02-17 12:46 UTC, Feldspatt requested changes
It looks good at the exception that the modal take all the height.

2023-02-17 12:50 UTC, Feldspatt approved these changes
I previously requested change as the modal was taking all the height. On the big screen it does not take all the scren.

2023-02-23 10:36 UTC, SteppbySteph commented
Conflicts now resolved.

2023-02-23 10:44 UTC, Feldspatt approved these changes

2023-02-23 11:02 UTC, lmeow approved these changes

2023-02-23 11:02 UTC, lmeow approved these changes

2023-02-23 11:02 UTC, merged